name: shell Commands

on: [push]

jobs:
 build-and-deploy:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    
    # dotnet build and publish
    - name: Build with dotnet
      run: dotnet build --configuration Release .\dotnet-core-webapp

    - name: dotnet publish 
      run: |
        dotnet publish -c Release -o dotnetcorewebapp .\dotnet-core-webapp
    - name: Deploy to IIS
      run: |
        iisreset /stop
        Copy-Item ./github-action-test/* C:/inetpub/wwwroot/git-action-test -Recurse -Force
        iisreset /start
    
    - name: Curl the website as a smoke test
      run: curl http://localhost/github-actions-test


    - name: Run Web Test
      run: |
        dotnet build --configuration Release .\github-action-test.webtest
        cd .\dotnet-core-webapp.webtests
        dotnet test









    
